solc:
    version: 0.5.6
    evm_version: null
    optimize: true
    runs: 200
    minify_source: false
dependencies:
  OpenZeppelin/openzeppelin-contracts@3.4.0
dotenv:
  .env
gas_limit:
  100000000000
